services:
  splunk:
    image: splunk/splunk:latest
    platform: linux/amd64
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_PASSWORD: "TestPassword123!"
    ports:
      - "18089:8089"
      - "18000:8000"
    volumes:
      - ./TA-epss:/opt/splunk/etc/apps/TA-epss
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-k",
          "-s",
          "https://localhost:8089/services/server/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
