[install]
build = 1
is_configured = false

[ui]
is_visible = true
label = EPSS Scores for Splunk

[launcher]
author = Jerry Gamblin
description = Ingests daily EPSS (Exploit Prediction Scoring System) scores from FIRST
version = 1.0.0

[package]
id = TA-epss
check_for_updates = false
