[install]
is_configured = false
state = enabled

[ui]
is_visible = true
label = EPSS Scores for Splunk

[launcher]
author = Jerry Gamblin
description = Ingests daily EPSS (Exploit Prediction Scoring System) scores from FIRST
version = 1.0.0

[id]
name = TA-epss
version = 1.0.0

[package]
id = TA-epss
check_for_updates = true
