[epss]
python.version = python3
python.required = 3.13

[epss://default]
index = main
lookback_days = 30
batch_size = 5000
epss_base_url = https://epss.empiricalsecurity.com
interval = 86400
disabled = 0
