[epss:score]
KV_MODE = json
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TIME_FORMAT = %Y-%m-%d
TIME_PREFIX = "score_date"\s*:\s*"
MAX_TIMESTAMP_LOOKAHEAD = 10
TRUNCATE = 10000

FIELDALIAS-vulnerability_id = cve_id AS vulnerability_id
FIELDALIAS-severity_score = epss_score AS severity_score
FIELDALIAS-signature = cve_id AS signature
FIELDALIAS-signature_id = cve_id AS signature_id
FIELDALIAS-severity = epss_risk_tier AS severity
FIELDALIAS-vendor_severity = epss_risk_tier AS vendor_severity

[epss:audit]
KV_MODE = json
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)
TIME_FORMAT = %Y-%m-%dT%H:%M:%S.%f
TIME_PREFIX = "timestamp"\s*:\s*"
TRUNCATE = 10000
